---

- name: Create a vip
  hosts: bigip
  connection: local
  tasks:

      - name: Create Pool
        bigip_pool:
            lb_method: least-connections-member
            user: "{{ ansible_user }}"
            password: "{{ ansible_password }}"
            name: ansible-test1
            monitors:
              - https
            slow_ramp_time: 120
            server: "{{ inventory_hostname }}"
            validate_certs: false
        delegate_to: localhost

      - name: Create node
        bigip_node:
            host: 10.10.10.10
            name: 10.10.10.10
            user: "{{ ansible_user }}"
            password: "{{ ansible_password }}"
            state: present
            partition: Common
            server: "{{ inventory_hostname }}"
            validate_certs: false
        delegate_to: localhost 