---

- name: Create a f5testvip
  hosts: bigips
  connection: local
  tasks:

      - name: Create VIP
        bigip_pool:
            lb_method: least-connections-member
            user: COF5ADMN03
            password: vM<Ye12D-Oh|wNZ
            name: ansible-test1
            monitors:
              - https
            slow_ramp_time: 120
            server: 10.98.14.68
            validate_certs: false
        delegate_to: localhost

