---
###### No variables need to be passed to this playbook ######
#
#  inventory_hostname: This is a built-on variable. You don't need to pass this in.
#  iApps_list: created by 'register:' to story the response
#
# Author: Nathan Pearce
###### https://github.com/npearce/F5-iApps_and_Ansible-playbooks ######

- name: Retrieve a list of iApps installed on F5 BIG-IP
  hosts: bigips
  connection: local
  gather_facts: no
  tasks:

  - name: Query iApp resource via BIG-IP REST API
    uri:
      url: https://{{ inventory_hostname }}/mgmt/tm/ltm/virtual/
      validate_certs: no
      user: COF5ADMN01
      password: :KyNI7o!a]F?mPe
      return_content: yes
    register: virtual

  - name: Print response
    debug: msg="{{ (virtual.content|from_json)["items"] }}"